### PR TITLE
Upgrade Crystal

### PR DESCRIPTION
**Pull request by hugoabonizio**
Hi @MakeNowJust!

I made some tiny changes to make the example work on newer crystal versions.

Let me know if it need more changes.

### CODE REVIEW

**Comment by makenowjust** [comment]
Could you remove `crake` from `development_dependencies` and rewrite `make.cr` as `Makefile`? I think it makes CI green.

**Comment by hugoabonizio** [comment]
It's returning some diffs, can you check if the expected output is still right?

**Comment by makenowjust** [comment]
No. `spec/expected.txt` should be updated.

**Comment by makenowjust** [comment]
@hugoabonizio Thank you!!

**Pull request merged**
